# Generated by Django 5.0.1 on 2024-02-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApi', '0003_thirth_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirth_model',
            name='gender',
            field=models.CharField(max_length=50),
        ),
    ]
