# Generated by Django 5.0.1 on 2024-02-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApi', '0004_alter_thirth_model_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirth_model',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
