# Generated by Django 5.0.1 on 2024-02-03 16:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApi', '0007_thirth_model_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='fourth_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('salary', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('class_in', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(verbose_name=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
